### ISSUE TITLE
Question about unorder messages code

### ISSUE THREAD

**Issue by GewoonMaarten** [Robadob/sp-2018-08#1]
I am curious about the purpose this code (line 270-283 in 2D code). Is it for benchmarking only or does it have functionality in the algortihm?

**Comment by Robadob** [comment]
I believe it was used for validation that the implementation was operating correctly. So it's in no way required for generating the data structure or performing near neighbours searches.

When generating the data structure, messages (agents) are sorted in order of their bin's index.
The neighbourhood search kernel, operates on the agents in this sorted order leading to output being created in the order of the messages.

This block of code un-sorts the output data to the initial order of agents, this allows results to be compared with those of the previous iteration of a second implementation (trying to compare floating point locations in multi-dimensional space can otherwise be a challenge due to compounded floating point inaccuracy).

**Comment by GewoonMaarten** [comment]
That clears it up. Thanks!
